In [4]:
import pandas as pd
import numpy as np
import io

from IPython.display import display
from ipywidgets import FileUpload

# Create uploader widget
uploader = FileUpload(accept='.csv', multiple=False)
display(uploader)

FileUpload(value={}, accept='.csv', description='Upload')

In [5]:
# Read uploaded file
if len(uploader.value) == 0:
    print("Please upload the Iris.csv file")
else:
    for filename, fileinfo in uploader.value.items():
        content = fileinfo['content']
        df = pd.read_csv(io.BytesIO(content))

    print("Iris dataset loaded successfully.")
    display(df.head())

Iris dataset loaded successfully.

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
filtered_df = df[df['PetalLengthCm']>5]
filtered_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica

In [7]:
pivot_table = pd.pivot_table(
    df,
    values='PetalLengthCm',
    index='Species',
    aggfunc='mean'
)
#display pivot table
pivot_table

                 PetalLengthCm
Species
Iris-setosa              1.464
Iris-versicolor          4.260
Iris-virginica           5.552

In [9]:
melted_df= pd.melt(
    df,
    id_vars=['Species'],
    value_vars=['SepalLengthCm', 'SepalWidthCm'],
    var_name='Feature',
    value_name='Value'
)
melted_df.head();

In [10]:
duplicate_count = df.duplicated().sum()
print("no. of duplicate rows",duplicate_count)

no. of duplicate rows 0

In [12]:

duplicates_count= df.duplicated().sum()
print("Number of duplicates rows:", duplicates_count)

Number of duplicates rows: 0

In [13]:
sepal_length_array = np.array(df['SepalLengthCm'])
mean_value = np.mean(sepal_length_array)
std_deviation =  np.std(sepal_length_array)
variance = np.var(sepal_length_array)

print("mean of sepal length",mean_value)
print("standard deviation of sepal length", std_deviation)
print("variance of sepal length", variance)

mean of sepal length 5.843333333333334
standard deviation of sepal length 0.8253012917851409
variance of sepal length 0.6811222222222223

In [14]:
species_info= pd.DataFrame({
    'Species': ['Iris-setosa','Iris-versicolor','Iris-virginica'],
    'Category':['Small','Medium','Large']
})

merged_df= pd.merge(df,species_info,on='Species')

merged_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Category
0,1,5.1,3.5,1.4,0.2,Iris-setosa,Small
1,2,4.9,3.0,1.4,0.2,Iris-setosa,Small
2,3,4.7,3.2,1.3,0.2,Iris-setosa,Small
3,4,4.6,3.1,1.5,0.2,Iris-setosa,Small
4,5,5.0,3.6,1.4,0.2,Iris-setosa,Small

In [15]:
sepal_data= np.array(df[['SepalLengthCm','SepalWidthCm']])

print("Original shapes:", sepal_data.shape)

reshaped_data= sepal_data.reshape(-1,2)

print("Reshaped shape:", reshaped_data.shape)
reshaped_data[:5]

Original shapes: (150, 2)
Reshaped shape: (150, 2)

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [16]:
merged_df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Category
0,1,5.1,3.5,1.4,0.2,Iris-setosa,Small
1,2,4.9,3.0,1.4,0.2,Iris-setosa,Small
2,3,4.7,3.2,1.3,0.2,Iris-setosa,Small
3,4,4.6,3.1,1.5,0.2,Iris-setosa,Small
4,5,5.0,3.6,1.4,0.2,Iris-setosa,Small